### PR TITLE
Prepare release 0.5.0

### PR DESCRIPTION
**Pull request by kulmann**

### CODE REVIEW

**Review by butonic — CHANGES_REQUESTED** [review]
please also add https://github.com/owncloud/ocis-glauth/pull/26 because it fixes searching for share recipients

**Comment by kulmann** [comment]
Rebased so that #26 is included as well

**Review by IljaN — APPROVED** [review]

**Comment by kulmann** [comment]
Screenshot 2020-07-23 at 16 36 14

hooray for github caching weirdly and wanting me to update. and then the update merge commit is empty... -.-

**Comment by kulmann** [comment]
https://github.com/owncloud/ocis-glauth/pull/27 included as well

**Review by butonic — APPROVED** [review]

**Pull request merged**
